#!/bin/sh
#
# CUPS configuration utility.
#
# Copyright © 2021-2022 by OpenPrinting.
# Copyright © 2007-2019 by Apple Inc.
# Copyright © 2001-2006 by Easy Software Products, all rights reserved.
#
# Licensed under Apache License v2.0.  See the file "LICENSE" for more
# information.
#

VERSION="2.4.2"
APIVERSION="2.4"
BUILD="cups-2.4.2"

prefix=/mnt/ong_share/Anuj/Timing-Multiuser-Protocols/conda_env
exec_prefix=/mnt/ong_share/Anuj/Timing-Multiuser-Protocols/conda_env
bindir=/mnt/ong_share/Anuj/Timing-Multiuser-Protocols/conda_env/bin
includedir=/mnt/ong_share/Anuj/Timing-Multiuser-Protocols/conda_env/include
libdir=/mnt/ong_share/Anuj/Timing-Multiuser-Protocols/conda_env/lib
datarootdir=/mnt/ong_share/Anuj/Timing-Multiuser-Protocols/conda_env/share
datadir=/mnt/ong_share/Anuj/Timing-Multiuser-Protocols/conda_env/share
sysconfdir=/mnt/ong_share/Anuj/Timing-Multiuser-Protocols/conda_env/etc
cups_datadir=/mnt/ong_share/Anuj/Timing-Multiuser-Protocols/conda_env/share/cups
cups_serverbin=/mnt/ong_share/Anuj/Timing-Multiuser-Protocols/conda_env/lib/cups
cups_serverroot=/mnt/ong_share/Anuj/Timing-Multiuser-Protocols/conda_env/etc/cups
INSTALLSTATIC=

# flags for compiler and linker...
CFLAGS=""
LDFLAGS="-Wl,-rpath,/mnt/ong_share/Anuj/Timing-Multiuser-Protocols/conda_env/lib"
LIBS="  -L/mnt/ong_share/Anuj/Timing-Multiuser-Protocols/conda_env/lib -lssl -lcrypto   -lz -lpthread -lm -lcrypt -lrt -L/mnt/ong_share/Anuj/Timing-Multiuser-Protocols/conda_env/lib  -lz"

# Check for local invocation...
selfdir=`dirname $0`

if test -f "$selfdir/cups/cups.h"; then
    CFLAGS="-I$selfdir"
    LDFLAGS="-L$selfdir/cups $LDFLAGS"
    libdir="$selfdir/cups"
else
    if test $includedir != /usr/include; then
	CFLAGS="$CFLAGS -I$includedir"
    fi

    if test $libdir != /usr/lib -a $libdir != /usr/lib32 -a $libdir != /usr/lib64; then
	LDFLAGS="$LDFLAGS -L$libdir"
    fi
fi


usage()
{
    echo "Usage: cups-config --api-version"
    echo "       cups-config --build"
    echo "       cups-config --cflags"
    echo "       cups-config --datadir"
    echo "       cups-config --help"
    echo "       cups-config --ldflags"
    echo "       cups-config [--image] [--static] --libs"
    echo "       cups-config --serverbin"
    echo "       cups-config --serverroot"
    echo "       cups-config --version"
    echo ""
    echo "Note: The cups-config utility is deprecated and will be removed in a future"
    echo "      version of CUPS.  Use the pkg-config utility instead."

    exit $1
}

if test $# -eq 0; then
    usage 1
fi

# Parse command line options
static=no

while test $# -gt 0; do
    case $1 in
	--api-version)
	    echo $APIVERSION
	    ;;
	--build)
	    echo $BUILD
	    ;;
	--cflags)
	    echo $CFLAGS
	    ;;
	--datadir)
	    echo $cups_datadir
	    ;;
	--help)
	    usage 0
	    ;;
	--image)
	    # Do nothing
	    ;;
	--ldflags)
	    echo $LDFLAGS
	    ;;
	--libs)
	    if test $static = no; then
	        libs="-lcups";
	    else
	        libs="$libdir/libcups.a $LIBS";
	    fi
	    echo $libs
	    ;;
	--serverbin)
	    echo $cups_serverbin
	    ;;
	--serverroot)
	    echo $cups_serverroot
	    ;;
	--static)
	    if test -z "$INSTALLSTATIC"; then
	        echo "WARNING: Static libraries not installed." >&2
	    else
	        static=yes
	    fi
	    ;;
	--version)
	    echo $VERSION
	    ;;
	*)
	    usage 1
	    ;;
    esac

    shift
done
